const DEFAULT_SETTINGS = {
  password : "raidisnotabackup",
  slideDuration : 10,
  playThemes : "true",
  genericThemes : "true",
  fade : "true",
  hideSettingsLinks : "false",
  theaterRoomMode : "false",
  plexIP : "",
  plexHTTPS : "false",
  plexPort : 32400,
  plexToken : "",
  pinNS : "false",
  hideUser: "false",
  onDemandLibraries : "",
  numberOnDemand : 2,
  onDemandRefresh : 30,
  sonarrURL : "",
  sonarrToken : "",
  sonarrCalDays : 3,
  sonarrPremieres : "false",
  radarrURL : "",
  radarrToken : "",
  radarrCalDays : 30,
  readarrURL : "",
  readarrToken : "",
  readarrCalDays : 60,
  hasArt : "false",
  shuffleSlides: "false",
  genres: "",
  custBrand: "",
  titleColour: "#FAFAD2",
  footColour: "#FAFAD2",
  bgColour: "#000000",
  enableNS: "true",
  enableOD: "true",
  enableSonarr: "true",
  enableRadarr: "true",
  enableReadarr: "true",
  filterRemote: "true",
  filterLocal: "true",
  filterDevices: "",
  filterUsers: "",
  odHideTitle: "false",
  odHideFooter: "false",
  enableCustomPictures: "false",
  enableCustomPictureThemes: "false",
  customPictureTheme: "default",
  serverID: "",
  sleepStart: "00:00",
  sleepEnd: "07:00",
  enableSleep: "false",
  nowScreening: "",
  comingSoon: "",
  onDemand: "",
  recentlyAdded: "",
  recentlyAddedDays: "0",
  iframe: "",
  playing: "",
  ebook: "",
  trivia: "",
  triviaFrequency: 300,
  triviaTimer: 15,
  triviaCategories: "",
  enableTrivia: "false",
  triviaNumber: "",
  contentRatings: "",
  enableAwtrix: "false",
  awtrixIP: "",
  enableLinks: "false",
  links: "",
  excludeLibs: ""
};

module.exports = DEFAULT_SETTINGS;