const DEFAULT_SETTINGS = {
  password : "raidisnotabackup",
  slideDuration : 10,
  playThemes : "true",
  genericThemes : "true",
  fade : "true",
  plexIP : "",
  plexHTTPS : "false",
  plexPort : 32400,
  plexToken : "",
  pinNS : "false",
  onDemandLibraries : "",
  numberOnDemand : 2,
  onDemandRefresh : 30,
  sonarrURL : "",
  sonarrToken : "",
  sonarrCalDays : 3,
  sonarrPremieres : "false",
  radarrURL : "",
  radarrToken : "",
  radarrCalDays : 30,
  hasArt : "false",
  shuffleSlides: "false",
  genres: "",
  custBrand: "",
  titleColour: "#FAFAD2",
  footColour: "#FAFAD2",
  bgColour: "#FAFAD2",
  enableNS: "true",
  enableOD: "true",
  enableSonarr: "true",
  enableRadarr: "true",
};

module.exports = DEFAULT_SETTINGS;