const DEFAULT_SETTINGS = {
  password : "raidisnotabackup",
  slideDuration : 10,
  refreshPeriod : 120,
  playThemes : "true",
  genericThemes : "true",
  fade : "true",
  plexIP : "",
  plexHTTPS : "false",
  plexPort : 32400,
  plexToken : "",
  onDemandLibraries : "",
  numberOnDemand : 2,
  onDemandRefresh : 120,
  sonarrURL : "",
  sonarrToken : "",
  sonarrCalDays : 175,
  sonarrPremieres : "true",
  radarrURL : "",
  radarrToken : "",
  radarrCalDays : 30,
}
